### ISSUE TITLE
Running main prints ffmpeg usage

### ISSUE THREAD

**Issue by TheBlackbird14** [Valenwe/Arstotzka-Generator#1]
When I run main I encounter no other issues but when the execution gets to the ffmpeg command part, ffmpeg just prints its information and usage, like when there is a syntax error in the command. There is no jail.mp4 created. ffmpeg works on its own, I've tried the builtin version and a standalone binary. Here is the console output (I have uncommented the line where it prints the command it runs):

```
./ffmpeg -hide_banner -loglevel error -stats -y -i temp.mp4 temp.mp3 -c:v libx264 -c:a aac -map 0:v:0 -map 1:a:0 jail.mp4
ffmpeg version N-111797-gf225f8d746-20230823 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13.1.0 (crosstool-NG 1.25.0.196_227d99d)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=aarch64-ffbuild-linux-gnu- --arch=aarch64 --target-os=linux --enable-gpl --enable-version3 --disable-debug --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-openssl --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --enable-libpulse --enable-libvmaf --enable-libxcb --enable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --disable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --disable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --enable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --disable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags=-pie --extra-libs='-ldl -lgomp' --extra-version=20230823
  libavutil      58. 17.100 / 58. 17.100
  libavcodec     60. 23.100 / 60. 23.100
  libavformat    60. 10.100 / 60. 10.100
  libavdevice    60.  2.101 / 60.  2.101
  libavfilter     9. 11.100 /  9. 11.100
  libswscale      7.  3.100 /  7.  3.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
Video successfully created as 'jail.mp4'.
Glory to Arstotzka.
```

**Comment by Valenwe** [comment]
Hello @TheBlackbird14 
From the output of the command, it seems there is a "-i" missing in the options.
The correct command should have "-i temp.mp4 -i temp.mp3" instead of "-i temp.mp4 temp.mp3".
I checked the code but it seems that the missing flag is still there. In any case you removed it, it's line 336 of `main.py`.

**Comment by TheBlackbird14** [comment]
Hi thanks for the quick answer. I forgot I removed that flag trying to fix it (I don't know a lot about ffmpeg). But the issue still persist, even if i revert the code to main branch. Is it possible this has something to do with my version of ffmpeg?

**Comment by TheBlackbird14** [comment]
Just tested it in a windows vm (I was using linux previously) and here it works just fine. Seems to be something with ffmpeg. Thanks for your help.

**Comment by Valenwe** [comment]
Oh it is possible that the encoding used in the command is one relative to Windows operating system only. Thought there might be a fix for that, i'll dig into it. Thank you for pointing out that bug :)

**Comment by Valenwe** [comment]
Okay I used ffmpeg from a Ubuntu operating system, and it seems to be working well so far. My version is different from yours though, so my guess is that you might have an outdated one, or do not have required libraries to mix audio and video together.
`ffmpeg version 6.0-5 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 13 (Debian 13.2.0-1)`
